application: googlockholmes13
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /site
  static_dir: templates  

- url: .*
  script: main.app

- url: /images/(.*) 
  static_files: static/images/\1 
  upload: static/images/(.*) 
 
  

  

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest